version: '2'

services:

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    ports:
      - 5433:5432

    environment:
      - POSTGRES_USER=content-listener
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=db.changelog/db-changelog-master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://localhost:5433/postgres
      - --username=content-listener
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend: {}