version: '2'

services:

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres_main
    ports:
      - 5433:5432

    environment:
      - POSTGRES_USER=content-listener
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    restart: always