name: Build Bot

on:
  push:
    paths:
      - 'bot/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn package -pl bot -am

      - name:
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bot.Dockerfile
          push: false
          tags: bot:latest