version: '2'

services:

  postgres:
    image: 'postgres:15.2-alpine'
    container_name: postgresql
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=content-listener
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scrapper
    restart: always
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=content-listener
      - --password=admin
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend: {}